# Generated by Django 4.2.2 on 2023-06-18 12:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Язык')),
                ('description', models.TextField(verbose_name='Описание')),
                ('level_learning', models.PositiveSmallIntegerField(verbose_name='Уровень изучения')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
            },
        ),
        migrations.CreateModel(
            name='Libraries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Библиотека')),
                ('description', models.TextField(verbose_name='Описание')),
                ('level_learning', models.PositiveSmallIntegerField(verbose_name='Уровень изучения')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.language', verbose_name='Языки')),
            ],
            options={
                'verbose_name': 'Библиотека',
                'verbose_name_plural': 'Библиотеки',
            },
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Инструмент')),
                ('description', models.TextField(verbose_name='Описание')),
                ('level_learning', models.PositiveSmallIntegerField(verbose_name='Уровень изучения')),
            ],
            options={
                'verbose_name': 'Инструмент',
                'verbose_name_plural': 'Инструменты',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('url_to_git', models.URLField(verbose_name='Ссылка на гит')),
                ('url_to_test', models.URLField(verbose_name='Ссылка на проект для тестирования')),
                ('date_start_project', models.DateField(default=datetime.date.today)),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Изображения проекта')),
                ('future_changes', models.TextField(verbose_name='Будущие изменения проекта')),
                ('slug_project', models.SlugField(max_length=150, unique=True)),
                ('draft', models.BooleanField(default=True, verbose_name='Черновик')),
                ('languages', models.ManyToManyField(to='model.language', verbose_name='Языки')),
                ('libraries', models.ManyToManyField(to='model.libraries', verbose_name='Бибилиотеки')),
                ('tools', models.ManyToManyField(to='model.tools', verbose_name='Инструменты')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
